###  ---------------------- SKILLS ----------------------
# @name createSkill 
POST http://localhost:3333/skills
Content-Type: application/json

{
  "name": "Api rest",
  "icon": "https://imgur.com/ajgDP2E"
}

###
@skillId = {{ createSkill.response.body._id }}
###

GET http://localhost:3333/skills

###
GET http://localhost:3333/skills/{{skillId}}


###

PATCH http://localhost:3333/skills/{{skillId}}
Content-Type: application/json

{
  "name": "react",
 "icon": "http://react"
}

###
DELETE http://localhost:3333/skills/{{skillId}}

#  ---------------------- TECHNOLOGIES ----------------------
###
# @name createTechnology
POST http://localhost:3333/technologies
Content-Type: application/json

{
  "name": "Spring Boot",
  "icon": "https://imgur.com/hGYSUGQ",
  "appIcon": "https://imgur.com/alHTVfD"
}

###

@technologyId = {{ createTechnology.response.body._id }}

###
GET http://localhost:3333/technologies

###
GET http://localhost:3333/technologies/{{technologyId}}

###
PATCH http://localhost:3333/technologies/{{technologyId}}
Content-Type: application/json

{
 "name": "spring",
  "icon": "http://spring",
  "appIcon": "http://spring"
}

###
DELETE http://localhost:3333/technologies/{{technologyId}}

#  ---------------------- PROJECTS ----------------------
###
# @name createProject
POST http://localhost:3333/projects
Content-Type: application/json

{
  "title": "Full Stack Spotify",
  "logo": "https://imgur.com/WgSZoYJ",
  "mockup": "https://imgur.com/Vy1SDmD",
  "repository": "full-stack-spotify",
  "siteUrl": "http://react.dev",
  "videoUrl": "http://react.dev",
  "stack": ["680a22be7c6442a8f0f3df51", "680a23417c6442a8f0f3df54"]
}

###
@projectId = {{ createProject.response.body._id }}

###
GET http://localhost:3333/projects

### 
GET http://localhost:3333/projects/{{ projectId }}

###
PATCH http://localhost:3333/projects/{{projectId}}
Content-Type: application/json

{
  "title": "react",
  "logo": "http://react",
  "mockup": "http:/react",
  "repository": "react",
  "siteUrl": "http://react",
  "videoUrl": "http://react",
  "stack": [
    "67fac495be08b8e50cc33122"
  ]
}

###
DELETE http://localhost:3333/projects/{{projectId}}