#  ---------------------- SKILLS ----------------------
# @name createSkill 
POST http://localhost:3333/skills
Content-Type: application/json

{
  "name": "TDDf",
  "icon": "TD"
}

###
@skillId = {{ createSkill.response.body._id }}
###

GET http://localhost:3333/skills

###
GET http://localhost:3333/skills/{{skillId}}


###

PATCH http://localhost:3333/skills/{{skillId}}
Content-Type: application/json

{

  "icon": "TD222"
}

###
DELETE http://localhost:3333/skills/67fa8067769f9789fa37f84f

#  ---------------------- TECHNOLOGIES ----------------------
###
POST http://localhost:3333/technologies
Content-Type: application/json

{
  "name": "c++",
  "icon": "icone",
  "appIcon": "app"
}

###
GET http://localhost:3333/technologies

###
GET http://localhost:3333/technologies/67faa6c324843b545e722c3d