###  ---------------------- SKILLS ----------------------
# @name createSkill 
POST http://localhost:3333/skills
Content-Type: application/json

{
  "name": "TDDf",
  "icon": "TD"
}

###
@skillId = {{ createSkill.response.body._id }}
###

GET http://localhost:3333/skills

###
GET http://localhost:3333/skills/{{skillId}}


###

PATCH http://localhost:3333/skills/{{skillId}}
Content-Type: application/json

{
"name": "react"
}

###
DELETE http://localhost:3333/skills/{{skillId}}

#  ---------------------- TECHNOLOGIES ----------------------
###
# @name createTechnology
POST http://localhost:3333/technologies
Content-Type: application/json

{
  "name": "spring teste",
  "icon": "icone",
  "appIcon": "app"
}

###

@technologyId = {{ createTechnology.response.body._id }}

###
GET http://localhost:3333/technologies

###
GET http://localhost:3333/technologies/{{technologyId}}

###
PATCH http://localhost:3333/technologies/{{technologyId}}
Content-Type: application/json

{
 
}

###
DELETE http://localhost:3333/technologies/{{technologyId}}